version: '3.8'

networks:
  backend:

services:
  sql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=patxWord
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=api-user
      - MYSQL_PASSWORD=patxWord 
    networks:
      - backend
    ports:
      - 3306:3306
    # volumes:
    #   - ./:/app/
    command: bash 
    tty: true

  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 8081:8081
    # volumes:
    #   - ./:/app/
    command: bash -c "ls ; node server.js"
    tty: true
    depends_on:
      - sql
    

  frontend:
    user: node
    image: node:16
    build:
      context: Frontend/angular-frontend
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - 4200:4200
    volumes:
      - ./Frontend/angular-frontend:/app
    #working_dir: /app
    command: bash -c "ls; npm run start"
    tty: true
      # - bash "ng serve --proxy-config proxy.conf.json"
    depends_on:
      - backend